In [3]:
import pandas as pd

df = pd.read_csv('sbux.csv')
df

date    open    high     low   close    volume  Name
0     2013-02-08  27.920  28.325  27.920  28.185   7146296  SBUX
1     2013-02-11  28.260  28.260  27.930  28.070   5457354  SBUX
2     2013-02-12  28.000  28.275  27.975  28.130   8665592  SBUX
3     2013-02-13  28.230  28.230  27.750  27.915   7022056  SBUX
4     2013-02-14  27.765  27.905  27.675  27.775   8899188  SBUX
...          ...     ...     ...     ...     ...       ...   ...
1254  2018-02-01  56.280  56.420  55.890  56.000  14690146  SBUX
1255  2018-02-02  55.900  56.320  55.700  55.770  15358909  SBUX
1256  2018-02-05  55.530  56.260  54.570  54.690  16059955  SBUX
1257  2018-02-06  53.685  56.060  53.560  55.610  17415065  SBUX
1258  2018-02-07  55.080  55.430  54.440  54.460  13927022  SBUX

[1259 rows x 7 columns]

In [7]:
# Or reading directly from the web:
df = pd.read_csv('https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/tf2.0/sbux.csv') # this will take a bit longer.
df

date    open    high     low   close    volume  Name
0     2013-02-08  27.920  28.325  27.920  28.185   7146296  SBUX
1     2013-02-11  28.260  28.260  27.930  28.070   5457354  SBUX
2     2013-02-12  28.000  28.275  27.975  28.130   8665592  SBUX
3     2013-02-13  28.230  28.230  27.750  27.915   7022056  SBUX
4     2013-02-14  27.765  27.905  27.675  27.775   8899188  SBUX
...          ...     ...     ...     ...     ...       ...   ...
1254  2018-02-01  56.280  56.420  55.890  56.000  14690146  SBUX
1255  2018-02-02  55.900  56.320  55.700  55.770  15358909  SBUX
1256  2018-02-05  55.530  56.260  54.570  54.690  16059955  SBUX
1257  2018-02-06  53.685  56.060  53.560  55.610  17415065  SBUX
1258  2018-02-07  55.080  55.430  54.440  54.460  13927022  SBUX

[1259 rows x 7 columns]

In [13]:
# Selecting a particular row:
# df[0][0] # this wont work

In [16]:
df.columns # returns set of columns called "SERIES"

Index(['date', 'open', 'high', 'low', 'close', 'volume', 'Name'], dtype='object')

In [18]:
df['date'] # selecting a particular serie

0       2013-02-08
1       2013-02-11
2       2013-02-12
3       2013-02-13
4       2013-02-14
           ...    
1254    2018-02-01
1255    2018-02-02
1256    2018-02-05
1257    2018-02-06
1258    2018-02-07
Name: date, Length: 1259, dtype: object

In [22]:
df[['open', 'close']] # NOTE: requires double square brackets ie.: [[]]

open   close
0     27.920  28.185
1     28.260  28.070
2     28.000  28.130
3     28.230  27.915
4     27.765  27.775
...      ...     ...
1254  56.280  56.000
1255  55.900  55.770
1256  55.530  54.690
1257  53.685  55.610
1258  55.080  54.460

[1259 rows x 2 columns]

In [25]:
type(df['open']) # THis is series

pandas.core.series.Series

In [27]:
type(df[['open','close']]) # this will be a dataframe (more than one serie)

pandas.core.frame.DataFrame

In [29]:
df.iloc[0] # uses index to locate a row.

date      2013-02-08
open           27.92
high          28.325
low            27.92
close         28.185
volume       7146296
Name            SBUX
Name: 0, dtype: object

In [32]:
df.loc[0] # gets rows using "label" from index, and not necessairly integer position. - see below.

date      2013-02-08
open           27.92
high          28.325
low            27.92
close         28.185
volume       7146296
Name            SBUX
Name: 0, dtype: object

In [34]:
df2 = pd.read_csv('sbux.csv', index_col = 'date') # opening file with an index column

In [38]:
df2.head() # will show "date" highlighted

open    high     low   close   volume  Name
date                                                     
2013-02-08  27.920  28.325  27.920  28.185  7146296  SBUX
2013-02-11  28.260  28.260  27.930  28.070  5457354  SBUX
2013-02-12  28.000  28.275  27.975  28.130  8665592  SBUX
2013-02-13  28.230  28.230  27.750  27.915  7022056  SBUX
2013-02-14  27.765  27.905  27.675  27.775  8899188  SBUX

In [40]:
df2.tail() # will show "date" highlighted as it is index

open   high    low  close    volume  Name
date                                                   
2018-02-01  56.280  56.42  55.89  56.00  14690146  SBUX
2018-02-02  55.900  56.32  55.70  55.77  15358909  SBUX
2018-02-05  55.530  56.26  54.57  54.69  16059955  SBUX
2018-02-06  53.685  56.06  53.56  55.61  17415065  SBUX
2018-02-07  55.080  55.43  54.44  54.46  13927022  SBUX

In [45]:
df2.loc['2018-02-05'] # since date is an index - this will work with loc method.

open         55.53
high         56.26
low          54.57
close        54.69
volume    16059955
Name          SBUX
Name: 2018-02-05, dtype: object

In [47]:
# df2.iloc['2018-02-05']  this will fail: i- stands fro integer in iloc

In [61]:
df2.iloc[1256] # this will work.

open         55.53
high         56.26
low          54.57
close        54.69
volume    16059955
Name          SBUX
Name: 2018-02-05, dtype: object

In [63]:
type(df2.loc['2013-02-08']) # this is series

pandas.core.series.Series

In [64]:
df[df['open'] > 64]

date   open    high    low  close   volume  Name
1087  2017-06-05  64.85  64.870  64.18  64.27  6809284  SBUX
1088  2017-06-06  64.22  64.350  64.05  64.16  5448439  SBUX
1089  2017-06-07  64.13  64.295  63.34  63.50  8364994  SBUX

In [68]:
type(df['open'] > 64) # this is a serie that matches open > 64

pandas.core.frame.DataFrame

In [69]:
type(df[df['open'] > 64]) # this will be a dataframe

pandas.core.frame.DataFrame

In [78]:
df['Name'] != 'SBUX' # any rows different than 'SBUX' - none found

0       False
1       False
2       False
3       False
4       False
        ...  
1254    False
1255    False
1256    False
1257    False
1258    False
Name: Name, Length: 1259, dtype: bool

In [82]:
type(df['Name'] != 'SBUX') # this will be Series as well.


pandas.core.series.Series

In [86]:
# NOw with numpy...
import numpy as np

In [89]:
A = np.arange(10) # memorize this.
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
df.values # dont want 'objects' when doing math!

array([['2013-02-08', 27.92, 28.325, ..., 28.185, 7146296, 'SBUX'],
       ['2013-02-11', 28.26, 28.26, ..., 28.07, 5457354, 'SBUX'],
       ['2013-02-12', 28.0, 28.275, ..., 28.13, 8665592, 'SBUX'],
       ...,
       ['2018-02-05', 55.53, 56.26, ..., 54.69, 16059955, 'SBUX'],
       ['2018-02-06', 53.685, 56.06, ..., 55.61, 17415065, 'SBUX'],
       ['2018-02-07', 55.08, 55.43, ..., 54.46, 13927022, 'SBUX']],
      dtype=object)

In [92]:
# particular series as numpy array: 

In [96]:
A = df[['open','close']].values
A

array([[27.92 , 28.185],
       [28.26 , 28.07 ],
       [28.   , 28.13 ],
       ...,
       [55.53 , 54.69 ],
       [53.685, 55.61 ],
       [55.08 , 54.46 ]])

In [99]:
type(A)

numpy.ndarray

In [118]:
B = df[['open','close']].to_numpy()
B

array([[27.92 , 28.185],
       [28.26 , 28.07 ],
       [28.   , 28.13 ],
       ...,
       [55.53 , 54.69 ],
       [53.685, 55.61 ],
       [55.08 , 54.46 ]])

In [120]:
np.allclose(A, B)

True

In [121]:
# Important: writing a dataframe to file

In [126]:
smalldf = df[['open', 'close']]
smalldf.to_csv('output.csv')

In [131]:
# !head output.csv

# When index column is not desired
smalldf.to_csv('output_no_index.csv', index=False)