In [4]:
import numpy as np

np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
10 * np.ones((2, 3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.random()

0.9952027631547826

In [15]:
np.random.random((2,3)) # Memorize this one

array([[0.9060457 , 0.14691803, 0.81772227],
       [0.70468693, 0.10999086, 0.86162933]])

In [17]:
np.random.randn(2,3)

array([[-6.03974465e-02, -9.83036178e-01,  1.66816985e+00],
       [ 1.83643296e+00, -3.46008631e-01,  4.14965145e-04]])

In [32]:
R = np.random.randn(10000)

In [34]:
R.mean()

0.008303369019276825

In [36]:
np.mean(R)

0.008303369019276825

In [38]:
R.var()

1.0066357543008895

In [48]:
R = np.random.randn(10000, 3)

In [53]:
np.shape(R)

(10000, 3)

In [64]:
R.mean(axis=0) # memorize this one

array([-0.00817234, -0.00340995, -0.0046615 ])

In [75]:
R.mean(axis=0).shape

(3,)

In [77]:
R.mean(axis=1).shape

(10000,)

In [79]:
R.mean().shape

()

In [86]:
np.cov(R.T)

array([[ 0.98240848, -0.01862517,  0.00595517],
       [-0.01862517,  0.9984532 ,  0.0042028 ],
       [ 0.00595517,  0.0042028 ,  0.98550952]])

In [88]:
np.cov(R, rowvar=False) # LOok it up

array([[ 0.98240848, -0.01862517,  0.00595517],
       [-0.01862517,  0.9984532 ,  0.0042028 ],
       [ 0.00595517,  0.0042028 ,  0.98550952]])

In [115]:
np.random.randint(0, 10, size=(3,3)) # memorize this one

array([[6, 9, 7],
       [7, 3, 2],
       [9, 1, 1]])

In [112]:
np.random.choice(10, size=(3,3)) # HOw is it different from randint?

array([[3, 4, 6],
       [7, 1, 5],
       [5, 9, 3]])