In [1]:
import numpy as np

In [2]:
L = [[1, 2], [3,4]]
L

[[1, 2], [3, 4]]

In [3]:
L[0]

[1, 2]

In [4]:
L[0][1]

2

In [5]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [6]:
A[0][1]

2

In [7]:
A[0,1] # This seems important.

2

In [8]:
A[:,0] # This seems important

array([1, 3])

In [9]:
A.T # This seem important.

array([[1, 3],
       [2, 4]])

In [10]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [11]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [13]:
B = np.array([[1, 2, 3], [4,5,6]])

In [19]:
A.dot(B.T) # This will fail as there are two different dimensions

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [22]:
np.linalg.det(A) # Important

-2.0000000000000004

In [37]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [39]:
A

array([[1, 2],
       [3, 4]])

In [43]:
np.linalg.inv(A).dot(A) # Important.!

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [53]:
np.trace(A) # Returns a sum of diagonal. SHould be similar to sum(np.diag(A))

5

In [59]:
np.trace(A.T) # Expecting 2+3 = 5

5

In [62]:
np.linalg.eig(A) # eigenvalues and right eigenvectors of a square array. https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [68]:

Lam, V = np.linalg.eig(A)

In [72]:
Lam

array([-0.37228132,  5.37228132])

In [74]:
V

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [78]:
V[:,0] * Lam[0] == A @ V[:,0] # @ = standard matrix multiplication, https://www.pluralsight.com/guides/overview-basic-numpy-operations

array([ True, False])

In [81]:
V[:,0] * Lam[0], A @ V[:,0] # LOok into this

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [90]:
A

array([[1, 2],
       [3, 4]])

In [98]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0]) # Returns True if two arrays are element-wise equal within a tolerance.

True

In [100]:
np.allclose(V @ np.diag(Lam), A @ V) # Returns True if two arrays are element-wise equal within a tolerance.

True