In [1]:
# Setting the enviornments in Visual Code first: https://code.visualstudio.com/docs/python/environments
# https://colab.research.google.com/drive/1VdLyfnop7Tt4wx4BmS6WHSSQg3n5wXrX
# arrays vs lists.

import numpy as np
import pandas as pd

In [2]:
L = [1,2,3] # standard non-numpy list
A = np.array([1,2,3]) # numpy-array

In [3]:
for e in A:
    print (e)


1
2
3


In [4]:
print (A)

[1 2 3]


In [5]:

L.append(5)
L

[1, 2, 3, 5]

In [6]:
A+np.array([4])


array([5, 6, 7])

In [7]:
A + np.array([4])

array([5, 6, 7])

In [8]:
# A.append(4)  - will not work.

In [9]:
A + np.array([-1, -5, -6])

array([ 0, -3, -3])

In [10]:
# THis will fail:
#np.array([1, 2, 3]) + np.array([5, 6, 7, 8])

In [11]:
2*A / 10

array([0.2, 0.4, 0.6])

In [12]:
# This will increase number count of elements in the array
2 * L

[1, 2, 3, 5, 1, 2, 3, 5]

In [13]:
L2 = []
for e in L:
    L2.append(e + 3)
print ("L: %s" % L)
print ("L2: %s" % L2)


L: [1, 2, 3, 5]
L2: [4, 5, 6, 8]


In [14]:
# This is interesting stuff:
L2 = []
L2 = [e + 3 for e in L]
print ("L2: ",  L2)

L2:  [4, 5, 6, 8]


In [15]:
L2 = []
for e in L:
    L2.append(e ** 2)
L2

[1, 4, 9, 25]

In [16]:
# Memorize this strange syntax:
L2 = [e ** 2 for e in L]
L2

[1, 4, 9, 25]

In [17]:
a = [i for i in range(1, 10)]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
A = np.array([1, 2, 3])

In [19]:
A**2

array([1, 4, 9])

In [20]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [21]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [22]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [23]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])